---
- name: hipchat apt repo
  apt_repository: repo='deb http://downloads.hipchat.com/linux/apt stable main' state=present

- name: apt-key
  apt_key: url=https://www.hipchat.com/keys/hipchat-linux.key state=present

- name: update the apt cache
  apt: update_cache=yes

- name: abstract packages
  apt:  pkg={{item}} state=latest
  with_items:
      - hipchat
