---
- name: virtualization | Download Virtualbox
  get_url: url={{ virtualbox_url }} dest={{ virtualbox_deb_package }}
  
- name: virtualization | Fix any broken depedencies
  sudo: yes
  command: apt-get -f -y install
  
# if it fails see http://askubuntu.com/questions/456183/what-does-unknown-media-type-in-type-all-all-mean
# Unknown media type in type 'all/all' 
- name: virtualization | Install Virtualbox
  sudo: yes
  command: dpkg --skip-same-version -i {{ virtualbox_deb_package }}
  
- name: virtualization | Download Vagrant
  get_url: url={{ vagrant_url }} dest={{ vagrant_deb_package }}
  
- name: virtualization | Install Vagrant
  sudo: yes
  command: dpkg --skip-same-version -i {{ vagrant_deb_package }}
